# Generated by Django 5.0.6 on 2024-05-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_story_date_modified_story_description_story_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragment',
            name='story_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.CharField(default='No description listed', max_length=200),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(default='Untitled', max_length=50),
        ),
    ]
