# Generated by Django 5.0.6 on 2024-05-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_fragment_story_id_alter_story_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragment',
            name='story_id',
            field=models.IntegerField(),
        ),
    ]
