# Generated by Django 5.0.6 on 2024-05-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_fragment_story_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.CharField(default='No description listed', max_length=200, null=True),
        ),
    ]
