# Generated by Django 5.0.6 on 2024-05-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_story_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
